language: ruby
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
rvm:
  - 2.0.0
  - ruby-head
  - jruby-9.0.1.0
deploy:
  provider: rubygems
  api_key:
    secure: clYHhpfYieW4ZMPlDwhdsxZAaca6Ltg8fSDtmQcNly40+fOhAhBnR+VFX6VODX3jx0Jv0MlIZRqWn4V9LVERaEMvKwSL2qNnk2sdMe9Kbh+lXD4auCjgHhFKXN6dzUfXmJYKzjuUaMtK4m7aBLKnm2JLm3omUa4c0Yrnj3qS/to=
  on:
    tags: true
    all_branches: true
    repo: tpbowden/zonebie-info
    rvm: 2.0.0
